
project_id = "ijudkzqfriazabiosnvb"

[functions.clerk-publishable-key]
verify_jwt = false

[functions.clerk-whoami]
verify_jwt = false


# Keep these core functions
[functions.email-sender-get]
verify_jwt = false

[functions.resend-send-email]
verify_jwt = false
